language: node_js
node_js:
  - "12.19.0"
script:
  - npm run docs
before_deploy:
  - npm run test -- --coverage || travis_terminate 1
  - npm run build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: docs
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key: $github_token
    file: $zip
    on:
      tags: true
after_deploy:
  - if [ ! -z  "$TRAVIS_TAG" ]; then
      npx cws-upload $cid $sec $tkn $zip $eid;
    fi
