language: node_js
node_js:
  - "12.19.0"

script:
  - npm run docs

env:
  global:
    - CC_TEST_REPORTER_ID=$cc_token

before_deploy:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

  - npm run test -- --coverage || travis_terminate 1
  - npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: pages
    on:
      branch: master
  - provider: releases
    skip_cleanup: true
    api_key: $github_token
    file: $zip
    on:
      tags: true

after_deploy:
  - if [ ! -z  "$TRAVIS_TAG" ]; then
      npx cws-upload $cid $sec $tkn $zip $eid;
    fi
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT
