name: Translate

on:
  push:
    branches: [ translations ]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm run translate
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update translations
          branch: master
          file_pattern: 'assets/locales/*.json i18n/*.json'
          commit_user_name: Actions Bot
          commit_user_email: mail@example.com
          commit_author: Actions <actions@github.com>
