name: Translate

on:
  push:
    branches: [ translate ]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm run translate
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Github action
          author_email: mail@example.com
          message: 'Translate to locales'
          add: '*.json'
